### ISSUE TITLE
Metadata Types Mismatch

### ISSUE THREAD

**Issue by yuvaltobias** [ejholmes/metaforce#14]
Any reason why the Metadata Types (http://rubydoc.info/gems/metaforce/Metaforce/Metadata/Types) are different from the ones that appear in the documentation (http://www.salesforce.com/us/developer/docs/api_meta/Content/file_based.htm)?

I've tried adding to package.xml some types that weren't there, and got an error...

**Comment by ejholmes** [comment]
Can you give an example of the metadata type that gave an error? My first guess would be that it's one of the new metadata types added in the v24 release, since the metadata types in Metaforce are currently base on v23.

**Comment by yuvaltobias** [comment]
I guess you're right! I haven't diffed this exactly, but for example all the rules -- criteriaBasedRules, ownerRules, rules. This also explains why I got a package.xml with v23.0 she I sent one with v24.0...

Thanks!

**Comment by yuvaltobias** [comment]
I went ahead and compared the list of supported components in the 0.5.3 Metaforce gem (lib/metaforce/types.rb) and the ones mentioned in the documentation for the v26.0 API (http://www.salesforce.com/us/developer/docs/dev_lifecycle/Content/plan_proj_meta_components.htm), and came up with following list of components that are not supported by the gem:
- Flow
- Folder
- Group
- Queue
- Role
- SecuritySetting
- Territory

Any idea when they will show up?

**Comment by ejholmes** [comment]
Probably not anytime soon. This gem is pretty much unmaintained by me right now since I don't have much use for it. Pull requests are welcome though.

**Comment by ejholmes** [comment]
I just released a new version of the gem (1.0.0a), which shouldn't have this problem. 1.0.x is a complete rewrite and the api isn't backwards compatible with 0.5.x.
