### ISSUE TITLE
Login to a Sandbox to a New Client

### ISSUE THREAD

**Issue by thegogz** [ejholmes/metaforce#19]
I want to use Metaforce for a project which will require me to display the metadata from two organizations side by side, these are both sandboxes. 

Initially I thought I'd use the example from the home page

``` ruby
client = Metaforce::Metadata::Client.new :username => 'username',
    :password => 'password',
    :security_token => 'security token')
```

However this doesn't give an option to login to a sandbox. Is there some way to do that when generating a new client in this manner?

**Comment by ejholmes** [comment]
You can do [`Metaforce.configuration.test = true`](https://github.com/ejholmes/metaforce/blob/develop/lib/metaforce/config.rb#L44) to connect to a sandbox.

**Comment by thegogz** [comment]
Ahh Thanks :)
