### ISSUE TITLE
Basic usage issue....

### ISSUE THREAD

**Issue by sherod** [ejholmes/metaforce#24]
I've run 'gem install metaforce' and installed the gem but this line of code:

client = Metaforce::MetaData::Client.new :username => 'username',
                                          :password => 'password',
                                          :security_token => 'security token'

Simply returns:

NameError: uninitialized constant Metaforce
  const_missing at org/jruby/RubyModule.java:2642
         (root) at main.rb:3

Am I doing something blatantly wrong?  The gem is appearing when I list it, version 0.5.3

**Comment by ejholmes** [comment]
Did you `require 'metaforce'`?

Also, looks like you're using jruby. The gem is untested on jruby, so no guarantee that it works.

**Comment by sherod** [comment]
No, it doesn't work on jruby.   

Reverting to c ruby has gotten me further along, but I have issues with nokogiri and other items and it looks like I need to sort out that all first.

**Comment by pfernandezaltimetrik** [comment]
Hello, I have the same error and I can't find which could be the cause...

uninitialized constant RetrieveController::Metaforce

I have installed the metaforce gem, 0.5.3, 1.0.6 and 1.0.7 and I'm requiring it with require 'metaforce' in the controller where I'm using it for the retrieve option.

Have you an idea of what I'm doing wrong?
