### ISSUE TITLE
Loss of Functionality?

### ISSUE THREAD

**Issue by ayork** [ejholmes/metaforce#35]
I recently started using this gem with some good success, following the tutorial in the following article:

http://wiki.developerforce.com/page/Metaforce:_A_Gem_for_Accessing_the_Force.com_Metadata_API_from_Ruby

Now simple calls don't seem to produce any results.

For example, client.list(:type => "Profile") results in "NoMethodError: undefined method `list' for #Metaforce::Metadata::Client"

Have some functions been recently deprecated? If so, what is the alternative to the "list"-type functions mentioned in the article?

**Comment by ejholmes** [comment]
Metaforce 0.5.x to 1.0.x was a complete rewrite, and some of the api interface has changed. You'd want to use [`.list_metadata`](https://github.com/ejholmes/metaforce/blob/master/lib/metaforce/metadata/client/file.rb#L17):

``` ruby
client.list_metadata('Profile')
```
