### ISSUE TITLE
Getting Started?

### ISSUE THREAD

**Issue by ayork** [ejholmes/metaforce#36]
As [this question](https://github.com/ejholmes/metaforce/issues/35) indicates, I'm new to this gem, so I may be missing something. However, even after reading the documentation, I'm a little lost as to how to get started.

Specifically, 
1. How do I pull just the visible fields for a given record type?
2. How do I pull picklist dependencies (values that should be visible in a dependent picklist given a selected value in the master picklist)?

Some basic examples of these kinds of calls would be a big help to new users of the gem.

Thanks!

**Comment by ejholmes** [comment]
1. Probably what you want is [`client.describe_layout(sobject, record_type_id=nil)`](https://github.com/ejholmes/metaforce/blob/master/lib/metaforce/services/client.rb#L39). It returns a Hashie::Mash'd [DescribeLayoutResult](http://www.salesforce.com/us/developer/docs/api/Content/sforce_api_calls_describelayout_describelayoutresult.htm).
2. It's not supported yet. [Restforce](https://github.com/ejholmes/restforce) will eventually support it, once I have the time to implement it. If you're curious, there's an implementation in a pull request for the databasedotcom gem at https://github.com/heroku/databasedotcom/pull/68

I'll admit that the documentation is somewhat lacking currently, but the gem is basically a thin wrapper around the [Metadata API](http://www.salesforce.com/us/developer/docs/api_meta/index.htm) and the [Services API](http://www.salesforce.com/us/developer/docs/api/index.htm), so most methods align with api calls (eg. describe_layout, list_metadata, send_email). Probably the best source of documentation right now for the gem is just perusing through the source code, which should be a fairly easy read.
