### ISSUE TITLE
Possible tmp_zip_file race in metaforce/job/retrieve.rb

### ISSUE THREAD

**Issue by whiskeyriver** [ejholmes/metaforce#37]
When extracting the retrieved zip contents the tempfile is suddenly removed. 

metaforce/job/retrieve/tmp_zip_file creates the tempfile using Tempfile.new, writes the zip content to that file, and then closes the tempfile returning the path. According to the Tempfile documentation the tempfile will be deleted after close the next time the GC runs. This leads to the file being removed during the extraction process.

In my local copy I've modified the tmp_zip_file method to create a tmpfile using the file-temp gem, and then explicitly delete the file post-extraction. I could provide a patch or a pull-request to merge this change in if you would like to use this solution.

**Comment by ejholmes** [comment]
Nice catch. A PR would be much appreciated. Thanks!

**Comment by whiskeyriver** [comment]
I've forked, committed to the fork, and sent a pull-request. This is my
first, so let me know if it didn't come through correctly.
