### ISSUE TITLE
"\xE2" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by gauravsingh2012** [ejholmes/metaforce#39]
When I try to use the rake command. I always get this error 

"\xE2" from ASCII-8BIT to UTF-8
["/home/gaurav/.rvm/gems/ruby-1.9.3-p327/gems/metaforce-1.0.5/lib/metaforce/job/retrieve.rb:84:in `tmp_zip_file'", "/home/gaurav
/.rvm/gems/ruby-1.9.3-p327/gems/metaforce-1.0.5/lib/metaforce/job/retrieve.rb:67:in`extract_to'", "/home/gaurav/.rvm/gems/ruby-
1.9.3-p327/gems/metaforce-1.0.5/lib/metaforce/job/retrieve.rb:66:in `block in extract_to'", "/home/gaurav/.rvm/gems/ruby-1.9.3-p
327/gems/metaforce-1.0.5/lib/metaforce/job.rb:186:in`call'", "/home/gaurav/.rvm/gems/ruby-1.9.3-p327/gems/metaforce-1.0.5/lib/m
etaforce/job.rb:186:in `block in trigger'", "/home/gaurav/.rvm/gems/ruby-1.9.3-p327/gems/metaforce-1.0.5/lib/metaforce/job.rb:18
5:in`each'", "/home/gaurav/.rvm/gems/ruby-1.9.3-p327/gems/metaforce-1.0.5/lib/metaforce/job.rb:185:in `trigger'", "/home/gaurav
/.rvm/gems/ruby-1.9.3-p327/gems/metaforce-1.0.5/lib/metaforce/job.rb:176:in`block (2 levels) in run_loop'", "/home/gaurav/.rvm/
gems/ruby-1.9.3-p327/gems/metaforce-1.0.5/lib/metaforce/job.rb:171:in `loop'", "/home/gaurav/.rvm/gems/ruby-1.9.3-p327/gems/meta
force-1.0.5/lib/metaforce/job.rb:171:in`block in run_loop'", "/home/gaurav/.rvm/gems/ruby-1.9.3-p327/gems/metaforce-1.0.5/lib/m
etaforce/job.rb:162:in `call'", "/home/gaurav/.rvm/gems/ruby-1.9.3-p327/gems/metaforce-1.0.5/lib/metaforce/job.rb:162:in`start_
heart_beat'", "/home/gaurav/.rvm/gems/ruby-1.9.3-p327/gems/metaforce-1.0.5/lib/metaforce/job.rb:41:in `perform'", "/home/gaurav/
.rvm/gems/ruby-1.9.3-p327/gems/metaforce-1.0.5/lib/metaforce/job/retrieve.rb:28:in`perform'", "/home/gaurav/ruby_workspace/Test
/Test_Metadata/app/scheduler/import_data.rb:92:in `importEverything'", "/home/gaurav/ruby_workspace/Test/Test_Metadata/lib/tasks
/scheduler.rake:24:in`block in <top (required)>'", "/home/gaurav/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/task.rb:22
8:in `call'", "/home/gaurav/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/task.rb:228:in`block in execute'", "/home/gaura
v/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/task.rb:223:in `each'", "/home/gaurav/.rvm/gems/ruby-1.9.3-p327/gems/rake-
10.0.3/lib/rake/task.rb:223:in`execute'", "/home/gaurav/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/task.rb:166:in `blo
ck in invoke_with_call_chain'", "/home/gaurav/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'", "
/home/gaurav/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/task.rb:159:in `invoke_with_call_chain'", "/home/gaurav/.rvm/ge
ms/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/task.rb:152:in`invoke'", "/home/gaurav/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/
lib/rake/application.rb:143:in `invoke_task'", "/home/gaurav/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/application.rb:
101:in`block (2 levels) in top_level'", "/home/gaurav/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/application.rb:101:in
 `each'", "/home/gaurav/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/application.rb:101:in`block in top_level'", "/home/
gaurav/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/application.rb:110:in `run_with_threads'", "/home/gaurav/.rvm/gems/ru
by-1.9.3-p327/gems/rake-10.0.3/lib/rake/application.rb:95:in`top_level'", "/home/gaurav/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.
0.3/lib/rake/application.rb:73:in `block in run'", "/home/gaurav/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/application
.rb:160:in`standard_exception_handling'", "/home/gaurav/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/application.rb:70:i
n `run'", "/home/gaurav/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/bin/rake:33:in`<top (required)>'", "/home/gaurav/.rvm/gems/r
uby-1.9.3-p327/bin/rake:23:in `load'", "/home/gaurav/.rvm/gems/ruby-1.9.3-p327/bin/rake:23:in`<main>'"]

This is how my code looks like in import_data.rb

client = Metaforce.new :username => "", :password => "", :security_token => ""
# manifest = Metaforce::Manifest.new(:custom_object => ['*'])
# =>  conn = PG.connect("localhost", 5432, '', '', "postgres", "postgres", "")

Metaforce::Job.disable_threading!
manifest = Metaforce::Manifest.new(:custom_object => ['*'])

client.retrieve_unpackaged(manifest)
  .extract_to('./src')
  .perform

but this works fine if i use it as a ruby application like if i run it as ruby import_data.rb
I am using ruby 1.9.3. Anybody has a fix for this?

Thanks

**Comment by sac7850** [comment]
I'm having the same issue when with:

manifest = Metaforce::Manifest.new(:custom_object => ['Account'])
        client.retrieve_unpackaged(manifest)
          .on_complete { |job| puts ""}
          .on_error { |job| puts ""}
          .extract_to('./tmp')
          .perform

in a controller:

Encoding::UndefinedConversionError in Controller#index

"\xEC" from ASCII-8BIT to UTF-8

**Comment by gauravsingh2012** [comment]
@sac7850.
Hi,
I have added a fix for this. In the meantime what you can do is go to your metaforce gem folder/lib/job and edit retrieve.rb. You'll see a method tmp_zip_file. Add file.binmode after the tmp file has been created to make it work locally.

**Comment by sac7850** [comment]
@gauravsingh2012

Great!  Thank you!

**Comment by ejholmes** [comment]
Fixed in db6036a
