### ISSUE TITLE
Connection with 1.0.5

### ISSUE THREAD

**Issue by mattyep** [ejholmes/metaforce#40]
Hello,

I built and installed the version 1.0.5 and I figure out that Metaforce.configuration.test has been replaced by "host" 2 month ago si I configured it with "test.salesforce.com"

I don't know if it's related but I can't connect anymore to a sandbox with the same code using metaforce 0.5.3. 
Savon send the SOAP message to salesforce but the body is quite empty (no login, no password). If I switch back to the 0.5.3, the connection get back.

So should I do something else between fetching 1.0.5 source code and building/installing it locally ?

Regards,

**Comment by mattyep** [comment]
I got it. On 0.5.3 we could just use the following syntax to configure the SFDC connection.
Metaforce.configure do |config|
    config.username = username
        config.password = password
        config.security_token = security_token
end 

But on 1.0.5, those parameters must be given to the client constructor directly. 

Was that behavior changed on purpose ?

**Comment by ejholmes** [comment]
Not on purpose. I'll add it back in eventually. You can also just specify the username, password and security token using env variables, and forego the initializer entirely:  https://github.com/ejholmes/metaforce#username-and-password
