### ISSUE TITLE
Compiling?

### ISSUE THREAD

**Issue by ViViDboarder** [ejholmes/metaforce#45]
So I'm new to Ruby but I was going to write a set of command line tools for integration into various editors and found that you've already done a good amount of the heavy lifting here.

As a result, I'd like to make a few changes and submit some pull requests to the project but I'm not sure how to compile this utility. I tried running `rake` from the project directory but I get

```
metaforce (master)$ rake
rake aborted!
cannot load such file -- rspec/core/rake_task
/Users/vividboarder/workspace/metaforce/Rakefile:6:in `<top (required)>'
/Users/vividboarder/.rvm/gems/ruby-1.9.3-p362/bin/ruby_noexec_wrapper:14:in `eval'
/Users/vividboarder/.rvm/gems/ruby-1.9.3-p362/bin/ruby_noexec_wrapper:14:in `<main>'
(See full trace by running task with --trace)
```

Any idea what this means? I'm probably missing a bunch of dependencies. I've also already executed `gem install metaforce` if that matters.

**Comment by ejholmes** [comment]
did you `bundle install` in the directory first?

**Comment by ViViDboarder** [comment]
Nope. That looks to have done it!

So, now, using this...

I see it spits out a binary file, I'm assuming that's the command line tool. If I wanted to use this in irb or in a ruby script, would I have to do anything special? Or did rake install it as a gem?

Sorry for the noobish questions.

**Comment by ejholmes** [comment]
When you ran `gem install metaforce` you got the binary and the library. So you can use the [command line tool](https://github.com/ejholmes/metaforce#command-line) or load up the library in irb/ruby scripts:

``` bash
~ $ irb
>> require 'metaforce'
=> true
```
