### ISSUE TITLE
will client.new accept oauth token instead of username & password?

### ISSUE THREAD

**Issue by sfielder** [ejholmes/metaforce#46]
Thanks

**Comment by se6wagner** [comment]
yes

Metaforce.new(:session_id => YOUR_OAUTH_TOKEN)

**Comment by sfielder** [comment]
awesome thx - great work btw

On Thu, Mar 28, 2013 at 4:00 PM, SBW notifications@github.com wrote:

> yes
> 
> Metaforce.new(:session_id => YOUR_OAUTH_TOKEN)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ejholmes/metaforce/issues/46#issuecomment-15611045
> .

## 

Regards,

Scott Fielder

**Comment by sfielder** [comment]
This is giving me (INVALID_LOGIN) INVALID_LOGIN: Invalid username, password, security token; or user locked out.

metaclient = Metaforce::Metadata::Client.new(:session_id => token)

**Able to authenticate successfully to databasedotcom gem with same token

Any thoughts on why session_id is being rejected when passed in as the option?

thx for your help

**Comment by sfielder** [comment]
See below request - 

Do I need to pass the instance_url as well or use abstract_client?

Thanks for your help

SOAP request: https://login.salesforce.com/services/Soap/u/23.0
SOAPAction: "login", Content-Type: text/xml;charset=UTF-8, Content-Length: 505
<?xml version="1.0" encoding="UTF-8"?><env:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xml
ns:tns="urn:partner.soap.sforce.com" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ins0="urn:partner.soap.sforce.com" xmlns:ins1="urn:sobjec
t.partner.soap.sforce.com" xmlns:ins2="urn:fault.partner.soap.sforce.com">env:Bodyins0:login<ins0:username xsi:nil="true"/><ins0:password xsi:nil="tru
e"/>/ins0:login/env:Body/env:Envelope
SOAP response (status 500):
<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:sf="urn:fault.partner.soap.sforce.
com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">soapenv:Bodysoapenv:Fault<faultcode>INVALID_LOGIN</faultcode><faultstring>INVALID_LOGIN: In
valid username, password, security token; or user locked out.</faultstring><detail><sf:LoginFault xsi:type="sf:LoginFault">sf:exceptionCodeINVALID_LOGIN
/sf:exceptionCodesf:exceptionMessageInvalid username, password, security token; or user locked out./sf:exceptionMessage/sf:LoginFault</detail></so
apenv:Fault>/soapenv:Body/soapenv:Envelope
