### ISSUE TITLE
Suppress/Parse Soap Response?

### ISSUE THREAD

**Issue by ViViDboarder** [ejholmes/metaforce#48]
I'm making a request using the following code:

```
@client.retrieve_unpackaged(File.expand_path(Atf_Config.src + '/package.xml')).
    extract_to(Atf_Config.src).
    on_complete { |job| puts "Finished retrieve #{job.id}!" }.
    on_error { |job| puts "Something bad happened!" }.
    perform
```

And I get a lot of xml written out. I'd like to suppress this or read it into another variable or stream that I can parse. Is there a way to suppress the printing and provide another callback function so that I can parse out the relevant parts on my own and print something more readable?

Some background if interested:

I'm writing another tool that is utilizing metaforce. It's primarily for use in command line with an interface similar to git for adding remotes and switching between them as well as pushing and pulling. The incentive for that is so that I could write a vim deploy plugin, which I have a preliminary version written already. You may be a vim user as I've forked and sent PRs to your vim-forcedotcom repo already.

Anyway, here are the repos: [abuse-the-force](https://github.com/ViViDboarder/abuse-the-force) and [vim-abuse-the-force](https://github.com/ViViDboarder/vim-abuse-the-force). The Ruby is probably bad. It's my first attempt at writing an app in Ruby.

I would have just done them as a PR to this repo, but I'm lost and still learning. When I have it more cleaned up I'll try if you like the ideas I'm coming up with.

**Comment by se6wagner** [comment]
@ViViDboarder same here, but I figured that I can disable the Savon log with

Metaforce.configuration.log=false

**Comment by ViViDboarder** [comment]
Awesome! Thanks @sebwagner. Worked like a charm.
